### PR TITLE
implement missing features and misc updates

### PR DESCRIPTION
**Pull request by yioneko**
Important modifications:

- The QR code for fine payment is just a picture bundled with source code, and currently no api request is needed.
- Separator for authors defaults to `", "`. See: https://github.com/yioneko/database-course-design-web/blob/8a27708445db6bc56cf0fbd1bd11f8e21d4212f8/common/constants.ts.

### CODE REVIEW

**Comment by yioneko** [comment]
@zsz12251665 Not sure whether the separator of authors is fine. I'll merge this if no changes are requested.

**Review by zsz12251665 — APPROVED** [review]
Common part seems fine to me.

**Comment by zsz12251665** [comment]
However, we do not implement the access point where the user has paid their fine and update the database, do we?

**Comment by yioneko** [comment]
Yes, there is no api interface change. I'll add one for it.

**Pull request merged**
